#!/bin/bash

# What modules, in what order
MODULES="cpuload ram uptime storage battery volume backlight date time"

# Modules that require an active internet connection
# ONLINE_MODULES="weather internet"
# Delay between showing the status bar
DELAY="0.01"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beggining of the status bar
RIGHT_PADDING="|"
LEFT_PADDING=" "
